services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    Ady\Bundle\CaptchaBundle\Contracts\CaptchaInterface:
      public: true
      tags: ['ady.captcha.captcha_challenge']

  Ady\Bundle\CaptchaBundle\Form\CaptchaType:
    public: true
    arguments:
      $session: '@session'
      $captchas: !tagged_iterator ady.captcha.captcha_challenge

  Ady\Bundle\CaptchaBundle\Captcha\:
    resource: '../../Captcha'
    public: false

  Ady\Bundle\CaptchaBundle\Service\:
    resource: '../../Service'
    public: false
